language: php

sudo: false

cache:
  directories:
    - ~/.composer/cache

services:
  - elasticsearch

matrix:
    - env: MONGO=2.6.5.5
      php: 5.6
      addons:
        apt:
          packages:
            - libav-tools
            - mongodb-org-server
          sources:
            - mongodb-upstart
    - env: MONGOPHP=3.0.5.6
      php: 5.6
      addons:
        apt:
          packages:
            - libav-tools
            - mongodb-org-server
          sources:
            - mongodb-3.0-precise

before_install:
  - printf "\n" |pecl install imagick
  - phpenv config-add .travis.php.ini

install:
  - composer install --prefer-dist

before_script:
  - until nc -z localhost 27017; do echo Waiting for MongoDB; sleep 1; done
  - php app/console orchestra:mongodb:fixtures:load --type=functional -e=test
  - php app/console orchestra:elastica:index:create -e=test
  - php app/console orchestra:elastica:schema:create -e=test
  - php app/console orchestra:elastica:populate -e=test

script:
  - phpunit -c app/ --testsuite=unit
  - phpunit -c app/ --testsuite=functional
  - ./test-js.sh
