version: '2'

services:
  oo_code:
      image: debian:jessie
      volumes:
          - ../:/var/www/openorchestra
          - ../../open-orchestra-front-demo/:/var/www/front-openorchestra
          - ../../open-orchestra-media-demo/:/var/www/media-openorchestra
          - ../../uploaded-files:/var/www/uploaded-files
      tty: true

  oo_mongo:
    image: mongo:3.0
    networks:
        - db
    ports:
      - 27017:27017

  oo_apache_php:
      build: apache-php
      networks:
          - db
          - els
          - varnish
      volumes_from:
          - oo_code
      ports:
        - 80:80

  oo_elasticsearch:
      image: elasticsearch
      networks:
          - els
      ports:
          - 9200:9200

  oo_varnish:
      image: million12/varnish
      volumes:
        - ./varnish/default.vcl:/etc/varnish/default.vcl
      networks:
          - varnish
      environment:
        - VARNISHD_PARAMS=-a :6081
      expose:
        - 6081
      ports:
        - 6081:6081

networks:
  db: {}
  varnish: {}
  els: {}